name: Send email using Quarto and blastula
on: 
  schedule:
    - cron: '18 22 * * *'
jobs:
  render:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies
        run: 
          R -e 'install.packages("dplyr")'
          R -e 'install.packages("tsibble")'
          R -e 'install.packages("rugarch")'
          R -e 'install.packages("readr")'
          R -e 'install.packages("yfR")'
          R -e 'install.packages("blastula")'
        shell: Rscript {0}
      - name: Script
        run: Rscript send_email.R
      - name: Commit files
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add output/*
          git commit -am "commit on $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
