name: Agendador

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: macos-latest

    steps:
 
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@v2

      - name: Instalar dependências
        run:  
          R -e 'install.packages("blastula")'

      - name: Executar código
        run: Rscript send_email.R
      - name: Debug
        run: ls -R  
      - name: Commit
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add --all
          git commit -am "add Data"
          git push
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
